### PR TITLE
fix: specs failing due to order

### LINKED ISSUE #6: Fix specs that fail on element order
We need to have a way to tell lutaml-model to retain element order as it comes in?

Tests that fail on element order:

```
  6) Metaschema XML round-trip conversion with file /Users/mulgogi/src/lutaml/metaschema/spec/fixtures/metaschema/test-suite/schema-generation/dates-times/datatypes-datetime_metaschema.xml performs lossless round-trip conversion
     Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
     
       DIFF 1: expected node: <assembly ref="child" max-occurs="unbounded">
               <group-as name="children"/>
             </assembly>
               actual node  : <field ref="field-datetime" max-occurs="unbounded">
                   <group-as name="field-datetimes"/>
                </field>
               diff from    : assembly
               diff to      : field
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'
```

```
       DIFF 1: expected node: <flag ref="global-flag"/>
               actual node  : <define-flag name="local-flag" as-type="token">
                <formal-name>Flag defined locally</formal-name>
                <description>Has a local definition</description>
             </define-flag>
               diff from    : flag
               diff to      : define-flag
     
       DIFF 2: expected node: <define-assembly name="global-assembly">
           <formal-name>Assembly defined globally</formal-name>
           <description>Has a global definition</description>
           <model>
             <field ref="global-field"/>
             <define-field as-type="string" name="local-field2">
               <formal-name>Field defined locally</formal-name>
               <description>Has a local definition</description>
             </define-field>
           </model>
         </define-assembly>
               actual node  : <define-flag name="global-flag" as-type="token">
             <formal-name>Flag defined globally</formal-name>
             <description>Has a global definition</description>
          </define-flag>
               diff from    : define-assembly
               diff to      : define-flag
     # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'
```

These specs fail because the generated output uses a different element order at the same level.

_Originally posted by @ronaldtse in https://github.com/lutaml/metaschema/issues/3#issuecomment-2423799190_

### PR DESCRIPTION
**Pull request by HassanAkbar**
Fixing specs that fails due to element order

fix #6

### CODE REVIEW

**Comment by HassanAkbar** [comment]
@ronaldtse Some of the specs that are failing now are due to a bug fix in `lutaml-model` that the default values were not being used before,

Now we have failures like

```
DIFF 1: expected node: <METASCHEMA xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" abstract="no">
.
.
.
actual node  : <METASCHEMA xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0">
```

The `abstract` attribute has a default value of `no`, set in `root.rb`.

**Comment by ronaldtse** [comment]
@HassanAkbar that means that similar to the “render_nil” option, we should have a “omit_default” option, such as when the value is the default, omit it from output.

**Comment by ronaldtse** [comment]
There is one spec that seems like a real error in lutaml-model:
```
  29) Metaschema XML round-trip conversion with file metaschema/test-suite/schema-generation/local-declarations/modules/module_metaschema.xml performs lossless round-trip conversion
      Failure/Error: expect(generated).to be_analogous_with(cleaned_xml_string)
      
        DIFF 1: expected node: <METASCHEMA xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" abstract="no">
          <schema-name>OSCAL Control Catalog Format</schema-name>
          <schema-version>1.0.0-milestone3</schema-version>
          <short-name>oscal-catalog</short-name>
          <namespace>http://csrc.nist.gov/ns/metaschema/test</namespace>
          <json-base-uri>http://csrc.nist.gov/ns/metaschema/test</json-base-uri>
          <remarks>
            <p>For exercising Metaschema semantics with respect to modular assembly and composition.</p>
          </remarks>
          <define-assembly scope="global">
            <formal-name>Assembly defined in a module</formal-name>
            <description>XXX</description>
            <define-flag as-type="string" required="no">
              <formal-name>Locally defined flag</formal-name>
              <description>XXX</description>
            </define-flag>
            <model>
              <field min-occurs="0" max-occurs="1" in-xml="WRAPPED"/>
              <field min-occurs="0" max-occurs="1" in-xml="WRAPPED"/>
              <define-field as-type="string" collapsible="no" min-occurs="0" max-occurs="1" in-xml="WRAPPED">
                <formal-name>Locally defined field</formal-name>
                <description>XXX</description>
              </define-field>
            </model>
          </define-assembly>
          <define-field as-type="string" scope="global">
            <formal-name>Field, defined in a module (global by default)</formal-name>
            <description>XXX</description>
          </define-field>
          <define-field as-type="string" scope="global">
            <formal-name>Field, defined in a module as 'local'</formal-name>
            <description>XXX</description>
          </define-field>
        </METASCHEMA>
                actual node  : <METASCHEMA xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" abstract="yes">
           <schema-name>OSCAL Control Catalog Format</schema-name>
           <schema-version>1.0.0-milestone3</schema-version>
           <short-name>oscal-catalog</short-name>
           <namespace>http://csrc.nist.gov/ns/metaschema/test</namespace>
           <json-base-uri>http://csrc.nist.gov/ns/metaschema/test</json-base-uri>
           <remarks>
              <p>For exercising Metaschema semantics with respect to modular assembly and composition.</p>
           </remarks>
          
           <define-assembly name="module-assembly">
              <formal-name>Assembly defined in a module</formal-name>
              <description>XXX</description>
              <!--<flag ref="top-level-flag"/>-->
              <define-flag name="local-flag">
                 <formal-name>Locally defined flag</formal-name>
                 <description>XXX</description>
              </define-flag>
              <model>
                 <field ref="module-global-field"/>
                 <field ref="module-top-level-local-field"/>
                 <define-field name="module-local-field">
                    <formal-name>Locally defined field</formal-name>
                    <description>XXX</description>
                 </define-field>
              </model>
           </define-assembly>
           
           <define-field name="module-global-field">
              <formal-name>Field, defined in a module (global by default)</formal-name>
              <description>XXX</description>
           </define-field>
           
           <define-field name="module-top-level-local-field" scope="local">
              <formal-name>Field, defined in a module as 'local'</formal-name>
              <description>XXX</description>
           </define-field> 
           
        </METASCHEMA>
                diff from    : abstract="no"
                diff to      : abstract="yes"
      # ./spec/metaschema_spec.rb:66:in `block (5 levels) in <top (required)>'
```

In this spec, `abstract` is set to `"yes"` but the generated XML says `"no"`. This is a bug in lutaml-model.

**Comment by HassanAkbar** [comment]
> There is one spec that seems like a real error in lutaml-model:

@ronaldtse Yes this is the same issue as https://github.com/lutaml/lutaml-model/issues/108, I Will open a PR for the fix shortly.

**Pull request merged**
